CREATE TABLE cities
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    country       VARCHAR(255),
    latitude      DOUBLE PRECISION,
    longitude     DOUBLE PRECISION,
    last_searched TIMESTAMP WITHOUT TIME ZONE,
    search_count  INTEGER,
    CONSTRAINT pk_cities PRIMARY KEY (id)
);

CREATE TABLE current_weather
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city_id             BIGINT                                  NOT NULL,
    timestamp           TIMESTAMP WITHOUT TIME ZONE,
    temperature         DOUBLE PRECISION,
    humidity            INTEGER,
    wind_speed          DOUBLE PRECISION,
    wind_direction      INTEGER,
    pressure            INTEGER,
    weather_main        VARCHAR(255),
    weather_description VARCHAR(255),
    sunset              TIMESTAMP WITHOUT TIME ZONE,
    sunrise             TIMESTAMP WITHOUT TIME ZONE,
    last_updated        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_current_weather PRIMARY KEY (id)
);

CREATE TABLE forecasts
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city_id             BIGINT                                  NOT NULL,
    forecast_date       TIMESTAMP WITHOUT TIME ZONE,
    temperature         DOUBLE PRECISION,
    wind_speed          DOUBLE PRECISION,
    wind_direction      INTEGER,
    pressure            INTEGER,
    humidity            INTEGER,
    weather_main        VARCHAR(255),
    weather_description VARCHAR(255),
    rain_volume         DOUBLE PRECISION,
    probability         DOUBLE PRECISION,
    CONSTRAINT pk_forecasts PRIMARY KEY (id)
);

ALTER TABLE current_weather
    ADD CONSTRAINT uc_current_weather_city UNIQUE (city_id);

ALTER TABLE current_weather
    ADD CONSTRAINT FK_CURRENT_WEATHER_ON_CITY FOREIGN KEY (city_id) REFERENCES cities (id);

ALTER TABLE forecasts
    ADD CONSTRAINT FK_FORECASTS_ON_CITY FOREIGN KEY (city_id) REFERENCES cities (id);